chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat_view, name="chat_view"),
    path("<int:receiver_id>/", views.get_chat_session, name="get_chat_session"),
    path("select-user", views.select_user_view, name="select_user_view"),
    path("pusher/auth/", views.pusher_authentication, name="pusher_authentication"),
    path("send-message/", views.send_message, name="send_message"),
]

healthConfig/urls.py
from django.contrib import admin
from django.urls import path, include
from healthScore import homepage_and_auth

urlpatterns = [
    path("", homepage_and_auth.homepage, name="homepage"),
    path("hs/", include("healthScore.urls")),
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls")),
]

hospitalManagement/hospitalManagement/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models
from healthScore.models import User


class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=False)
    createdAt = models.DateTimeField(auto_now_add=True)


class ChatSession(models.Model):
    patient = models.ForeignKey(
        User, related_name="patient_chats", on_delete=models.CASCADE
    )
    healthcareWorker = models.ForeignKey(
        User, related_name="worker_chats", on_delete=models.CASCADE
    )
    createdAt = models.DateTimeField(auto_now_add=True)
    messages = models.ManyToManyField(Message, blank=True)

chat/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from healthConfig.settings import (
    PUSHER_APP_ID,
    PUSHER_KEY,
    PUSHER_SECRET,
    PUSHER_CLUSTER,
)
from healthScore.models import User, Hospital
from .models import ChatSession, Message
from pusher import Pusher
from django.views.decorators.csrf import csrf_exempt

pusher = Pusher(
    app_id=PUSHER_APP_ID,
    key=PUSHER_KEY,
    secret=PUSHER_SECRET,
    cluster=PUSHER_CLUSTER,
    ssl=True,
)


@login_required(login_url="/")
def get_chat_session(request, receiver_id):
    sender = request.user
    receiver = get_object_or_404(User, id=receiver_id)

    if sender.is_patient:
        # current chat and messages
        chat, created = ChatSession.objects.get_or_create(
            patient=sender, healthcareWorker=receiver
        )
        messages = chat.messages.all()
        # users that have been chatted with current user before
        receiver_ids = (
            ChatSession.objects.filter(patient_id=sender.id)
            .order_by("-createdAt")
            .values_list("healthcareWorker_id", flat=True)
            .distinct()
        )
        receivers = User.objects.filter(id__in=receiver_ids)
        receivers = list(receivers)
        receivers.sort(key=lambda receiver: list(receiver_ids).index(receiver.id))
    elif sender.is_healthcare_worker:
        # current chat and messages
        chat, created = ChatSession.objects.get_or_create(
            patient=receiver, healthcareWorker=sender
        )
        messages = chat.messages.all()
        # users that have been chatted with current user before
        receiver_ids = (
            ChatSession.objects.filter(healthcareWorker_id=sender.id)
            .order_by("-createdAt")
            .values_list("patient_id", flat=True)
            .distinct()
        )
        receivers = User.objects.filter(id__in=receiver_ids)
        receivers = list(receivers)
        receivers.sort(key=lambda receiver: list(receiver_ids).index(receiver.id))

    context = {
        "receiver_id": receiver_id,
        "receiver": receiver,
        "receivers": receivers,
        "messages": messages,
        "pusher_key": PUSHER_KEY,
    }

    return render(request, "chat/chat.html", context)


def chat_view(request):
    # get all chat sessions related to current user
    chat_log = (
        ChatSession.objects.filter(patient=request.user)
        .union(ChatSession.objects.filter(healthcareWorker=request.user))
        .order_by("-createdAt")
    )

    if chat_log.exists():
        # if it exists, load the latest chat
        first_chat = chat_log.first()
        print(first_chat.healthcareWorker.id, first_chat.patient.id)
        return redirect(
            "chat:get_chat_session",
            receiver_id=(
                first_chat.healthcareWorker.id
                if request.user == first_chat.patient
                else first_chat.patient.id
            ),
        )
    else:
        return render(request, "chat/no_chat.html")


@login_required(login_url="/")
def select_user_view(request):
    hospitals = Hospital.objects.all()
    return render(request, "chat/select_user.html", {"hospitals": hospitals})


@csrf_exempt
def pusher_authentication(request):
    channel_name = request.POST["channel_name"]
    print(channel_name)
    if channel_name.startswith(
        f"private-chat-{request.user.id}-"
    ) or channel_name.endswith(f"-{request.user.id}"):
        auth = pusher.authenticate(
            channel=channel_name, socket_id=request.POST["socket_id"]
        )
        return JsonResponse(auth)
    return JsonResponse({"message": "Forbidden"}, status=403)


def get_channel_name(author_id, other_user_id):
    if int(author_id) < int(other_user_id):
        return f"private-chat-{author_id}-{other_user_id}"
    else:
        return f"private-chat-{other_user_id}-{author_id}"


@csrf_exempt
def send_message(request):
    if request.method == "POST":
        content = request.POST.get("message")
        author_id = request.POST.get("author_id")
        other_user_id = request.POST.get("receiver_id")

        channel_name = get_channel_name(author_id, other_user_id)

        pusher.trigger(
            channel_name,
            "new_message",
            {"author_id": author_id, "receiver_id": other_user_id, "message": content},
        )

        author = User.objects.get(id=author_id)
        other_user = User.objects.get(id=other_user_id)

        new_message = Message.objects.create(author=author, content=content)
        chat_session, created = ChatSession.objects.get_or_create(
            patient=author if author.is_patient else other_user,
            healthcareWorker=author if author.is_healthcare_worker else other_user,
        )

        chat_session.messages.add(new_message)

        return JsonResponse(
            {"status": "success", "message": "Message sent successfully"}
        )
    else:
        return JsonResponse(
            {"status": "error", "message": "Invalid request"}, status=400
        )

chat/templates/chat/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Score</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        #full-container {
            display: flex;
            height: 100vh;
        }

        .chat-sidebar {
            flex: 1;
            background-color: #ECE8F9;
            padding: 20px;
            border-right: 2px solid #ccc; 
        }

        .chat-sidebar-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

            .chat-sidebar-header h2 {
                margin: 0; 
            }

        .chat {
            flex: 3;
            display: flex;
            flex-direction: column;
            padding: 20px;
            overflow-y: auto;
        }

        .chat-header {
            display: flex;
            align-items: center;
            margin-bottom: 30px;
        }

            .profile-picture {
                width: 55px; 
                height: 55px; 
                border-radius: 50%; 
                margin-right: 10px; 
            }

            .user-name {
                font-size: 20px; 
                font-weight: bold;
            }

        .chat-list {
            list-style-type: none;
            padding: 0;
        }

        .chat-list-item {
            cursor: pointer;
            padding: 15px; 
            border-bottom: 2px solid #ccc; 
            transition: background-color 0.3s; 
            font-size: 18px; 
        }

        .chat-list-item:hover {
            background-color: #f0f0f0; 
        }

        .chat-list-item.active {
            background-color: #8f68a3;
            color: #FFFFFF;
            font-weight: bold;
        }
        #messages {
            overflow-y: auto;
        }

        .message-container {
            display: flex;
            margin-bottom: 10px;
        }

        .message-container .message {
            max-width: 70%;
            padding: 10px;
            border-radius: 20px;
            margin-bottom: 5px;
            word-wrap: break-word;
            background-color: #f2f2f2;
        }

        .outgoing-message {
            display: flex;
            justify-content: flex-end;
        }

            .outgoing-message .message-container {
                justify-content: flex-end; 
            }

            .outgoing-message .message {
                background-color: #DCF8C6;
                color: #000; 
            }

        .incoming-message {
            display: flex;
            justify-content: flex-start; 
        }

            .incoming-message .message-container {
                justify-content: flex-start;
            }

            .incoming-message .message {
                background-color: #F2F2F2;
                color: #000; 
            }

        .message-input-container {
            margin-top: auto;
            display: flex;
            align-items: center;
        }

        .message-input {
            flex: 1;
            padding: 17px;
            font-size: 14px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .send-button {
            margin-left: 10px;
            padding: 18px 25px;
            font-size: 14px;
            background-color: #5B0888;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

            .send-button:hover {
                background-color: #2d0444;
                text-decoration: none;
                color: white
            }

        .create-button {
            padding: 10px 20px;
            background-color: #5B0888;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

            .create-button:hover {
                background-color: #2d0444;
                text-decoration: none;
            }
    </style>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    {%  include 'header.html' %}
    
    <div id="full-container">
        <div class="chat-sidebar">
            <div class="chat-sidebar-header">
                <h2>Your Chats</h2>
                <a href="{% url 'chat:select_user_view' %}" class="create-button">New Chat</a>
            </div>

            <ul class="chat-list" id="chatList">
                <!-- user chat list here -->
                {% for receiver in receivers %}
                {% if receiver.id == receiver_id %}
                <li class="chat-list-item active" data-receiver-id="{{receiver.id}}">{{receiver.name}}</li>
                {% else %}
                <li class="chat-list-item" data-receiver-id="{{receiver.id}}">{{receiver.name}}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>


        <div class="chat" id="chatInterface">
            <div class="chat-header">
                <img src="{{receiver.profilePic}}" alt="Profile Picture" class="profile-picture"> 
                <h2 class="user-name">{{receiver.name}}</h2>
            </div>

            <div id="messages">
                <!-- chat messages here -->
                {% for message in messages %}
                {% if message.author == user %}
                <div class="message-container outgoing-message">
                    <div class="message">{{message.content}}</div>
                </div>
                {% else %}
                <div class="message-container incoming-message">
                    <div class="message">{{message.content}}</div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="message-input-container">
                <input type="text" id="messageInput" class="message-input" placeholder="Type a message...">
                <button id="messageSubmit" onclick="sendMessage()" class="send-button">Send</button>
            </div>
        </div>
    </div>

    <script>
        var headerHeight = document.querySelector('header').offsetHeight;
        var fullContainerHeight = `calc(100vh - ${headerHeight}px)`;
        var fullContainer = document.querySelector('#full-container');
        fullContainer.style.height = fullContainerHeight;
        window.onload = function() {
            document.getElementById('messages').scrollTop = document.getElementById('messages').scrollHeight;
        };

        document.querySelector('#messageInput').focus();
        document.querySelector('#messageInput').onkeyup = function(e) {
            if (e.keyCode === 13){ // enter, return
                document.querySelector('#messageSubmit').click();
            }
        };

        var pusher = new Pusher('{{pusher_key}}', { cluster: 'us3', encrypted: true, authEndpoint: '{% url "chat:pusher_authentication" %}', });
        var channel;
        var userId = '{{ request.user.id }}';
        var otherUserId = '{{receiver_id}}';
        var channelName = parseInt(userId) < parseInt(otherUserId) ? `private-chat-${userId}-${otherUserId}` : `private-chat-${otherUserId}-${userId}`;
        channel = pusher.subscribe(channelName);
        channel.bind('new_message', function(data) {
            const messageContainer = document.createElement('div');
            messageContainer.classList.add('message-container');
            if (data.author_id === "{{request.user.id}}") {
                messageContainer.classList.add('outgoing-message');
            } else {
                messageContainer.classList.add('incoming-message');
            }
            const message = document.createElement('div');
            message.classList.add('message');
            message.textContent = data.message;
            messageContainer.appendChild(message);
            document.getElementById('messages').appendChild(messageContainer);
            document.getElementById('messages').scrollTop = document.getElementById('messages').scrollHeight;
        });

        function sendMessage() {
            var messageInput = document.getElementById('messageInput');
            var message = messageInput.value;
            if (message.trim() === '') {
                alert("Message cannot be empty.");
                return;
            }
            if (channel) {
                $.ajax({
                    url: '{% url "chat:send_message" %}', 
                    method: 'POST',
                    data: {
                        'message': message,
                        'author_id': '{{ request.user.id }}',
                        'receiver_id': '{{ receiver_id }}',
                    },
                    success: function(response) {
                        console.log(response.message);
                        messageInput.value = ''; 
                    },
                    error: function() {
                        alert("There was a problem sending the message.");
                    }
                });
            } else {
                alert("Please select a user to chat with first.");
            }
        }
        // click on chat list item to load chat
        document.querySelectorAll('.chat-list-item').forEach(function(chatListItem) {
            chatListItem.onclick = function(e) {
                const receiverId = chatListItem.getAttribute('data-receiver-id');
                window.location.href = '{% url "chat:get_chat_session" receiver_id=0 %}'.replace('0', receiverId);
            };
        });
    </script>
</body>
</html>

chat/templates/chat/no_chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Score</title>
    <style>
     body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        #full-container {
            display: flex;
            height: 100vh;
        }

        .chat-sidebar {
            flex: 1;
            background-color: #ECE8F9;
            padding: 20px;
            border-right: 2px solid #ccc; 
        }

        .chat-sidebar-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

            .chat-sidebar-header h2 {
                margin: 0; 
            }

        .chat {
            flex: 3;
            display: flex;
            flex-direction: column;
            padding: 20px;
            overflow-y: auto;
        }

        .chat-header {
            display: flex;
            align-items: center;
            margin-bottom: 30px;
        }

        .profile-picture {
            width: 55px; 
            height: 55px; 
            border-radius: 50%; 
            margin-right: 10px; 
        }

        .user-name {
            font-size: 20px; 
            font-weight: bold;
        }

        .chat-list {
            list-style-type: none;
            padding: 0;
        }

        .chat-list-item {
            cursor: pointer;
            padding: 15px; 
            border-bottom: 2px solid #ccc; 
            transition: background-color 0.3s; 
            font-size: 18px; 
        }

        .chat-list-item:hover {
            background-color: #f0f0f0; 
        }

        .chat-list-item.active {
            background-color: #8f68a3;
            color: #FFFFFF;
            font-weight: bold;
        }

        .message-container {
            display: flex;
            margin-bottom: 10px;
        }

        .message-container .message {
            max-width: 70%;
            padding: 10px;
            border-radius: 20px;
            margin-bottom: 5px;
            word-wrap: break-word;
            background-color: #f2f2f2;
        }

        .outgoing-message {
            display: flex;
            justify-content: flex-end;
        }

        .outgoing-message .message-container {
            justify-content: flex-end; 
        }

        .outgoing-message .message {
            background-color: #DCF8C6;
            color: #000; 
        }

        .incoming-message {
            display: flex;
            justify-content: flex-start; 
        }

        .incoming-message .message-container {
            justify-content: flex-start;
        }

        .incoming-message .message {
            background-color: #F2F2F2;
            color: #000; 
        }

        .message-input-container {
            margin-top: auto;
            display: flex;
            align-items: center;
        }

        .message-input {
            flex: 1;
            padding: 17px;
            font-size: 14px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .send-button {
            margin-left: 10px;
            padding: 18px 25px;
            font-size: 14px;
            background-color: #5B0888;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

            .send-button:hover {
                background-color: #2d0444;
                text-decoration: none;
                color: white
            }

        .create-button {
            padding: 10px 20px;
            background-color: #5B0888;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .create-button:hover {
            background-color: #2d0444;
            text-decoration: none;
        }
    </style>
</head>



<body>
    {%  include 'header.html' %}

    <div id="full-container">
        <div class="chat-sidebar">
            <div class="chat-sidebar-header">
                <h2>Your Chats</h2>
                <a href="{% url 'chat:select_user_view' %}" class="create-button">New Chat</a>
            </div>

            <ul class="chat-list" id="chatList">
                <!-- user chat list here -->
            </ul>
        </div>


        <div class="chat" id="chatInterface">
            <p>No chats available</p>
        </div>
    </div>

    <script>
        var headerHeight = document.querySelector('header').offsetHeight;
        var fullContainerHeight = `calc(100vh - ${headerHeight}px)`;
        var fullContainer = document.querySelector('#full-container');
        fullContainer.style.height = fullContainerHeight;
    </script>
</body>
</html>

chat/templates/chat/select_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Score</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .page-container {
            width: 95%;
            padding: 20px;
        }

        .search-container {
            display: flex;
            align-items: center;
        }

        .search-bar {
            flex: 7;
            padding: 10px;
            border: 2px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
            width: 70%;
        }

        .user-type-dropdown {
            flex: 2;
            padding: 10px;
            font-size: 16px;
            margin-left: 10px;
            width: 100%;
            appearance: none;
            background-image: url('https://icons.veryicon.com/png/o/miscellaneous/linktrip/down-arrow-small.png');
            background-repeat: no-repeat;
            background-position: right 10px center;
            background-size: 18px;
            border: 2px solid #ccc;
            border-radius: 5px;
            cursor: pointer;
        }

        .search-button {
            flex: 1;
            padding: 10px 20px;
            background-color: #5B0888;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-left: 10px;
        }

            .search-button:hover {
                background-color: #2d0444;
            }

        .back-button,
        .back-button:hover {
            display: block;
            margin-bottom: 20px;
            font-size: 16px;
            text-decoration: none;
            color: #5B0888;
        }
            .back-button:hover {
                color: #2d0444;
            }

        .patient-container {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
        }
            .patient-container:hover {
                background-color: #f0f0f0; 
            }

        .profile-picture {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            background-size: cover;
            background-position: center;
            margin-right: 40px;
        }

        .patient-details {
            flex-grow: 2;
        }

        .chat-button {
            padding: 15px 30px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
        }
            .chat-button:hover {
                background-color: #357937;
            }


    </style>
</head>
<body>
    {%  include 'header.html' %}

    <div class="page-container">
        <a href="{% url 'chat:chat_view' %}" class="back-button"> &#60; Back</a>
        <h2>Start a New Chat</h2>

        {% if user.is_patient %}
        <div class="search-container">
            <select id="hospitalSelect" class="user-type-dropdown" >
                <option value="" disabled selected>Select a Hospital</option>
                {% for hos in hospitals %}
                <option value="{{hos.id}}">{{hos.name}}</option>
                {% endfor %}
            </select>

            <select id="doctorSelect" class="user-type-dropdown" >
                <option value="" disabled selected>Select a healthcare worker...</option>
            </select>
        </div>

        {% elif user.is_healthcare_worker %}
        <div class="search-container">
            <select id="patientSelect" class="user-type-dropdown" >
                <option value="" disabled selected>Select a patient name...</option>
            </select>
        </div>
        {% endif %}
        <br><br>
        <div class="search-results"></div>
        
    </div>



<script>
    const hospitalDropdown = document.getElementById('hospitalSelect');
    if (hospitalDropdown) {
        hospitalDropdown.addEventListener('change', function(){
            const selectedOption = this.options[this.selectedIndex];
            const hospitalId = selectedOption.value; // get the selected hospital's ID
            const hospitalName =  selectedOption.textContent;// get the selected hospital name

            if (hospitalId) {
                fetch('{% url "get_doctors" hos_id=0 %}'.replace('0', hospitalId),{
                            method: 'GET',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                    })
                    .then(response => response.json())
                    .then(data => {
                        var selectElement = document.getElementById("doctorSelect");
                        selectElement.innerHTML = '<option value="" selected disabled>Please select doctors in '+ hospitalName +'</option>';

                        data['doctors'].forEach(function (doctor) {
                            var option = new Option(doctor.name, doctor.id);
                            selectElement.add(option);
                        });
                        
                    })
                    .catch((error) => {
                        console.error('Error:', error);
                    });
            }
        })
    }
  
    const doctorDropdown = document.getElementById('doctorSelect');
    if (doctorDropdown) {
        doctorDropdown.addEventListener('change', function(){
            const doctorId = this.value;
            fetch('{% url "get_doctor_details" doctor_id=0 %}'.replace('0', doctorId), {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                },
            })
            .then(response => response.json())
            .then(data => {
                console.log(data['user'])
                displaySearchResults(data['user'])
            })
        })
    }

    const patientDropdown = document.getElementById('patientSelect');
    if (patientDropdown) {
        window.onload = function(){
        fetch('{% url "get_patients" %}', {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            },
        })
        .then(response => response.json())
        .then(data => {
            console.log(data['patients'])
            data['patients'].forEach(function (patient) {
                var option = new Option(patient.name, patient.id);
                patientDropdown.add(option);
            });
        })
        .catch((error) => {
            console.error('Error:', error);
        });
        }
        patientDropdown.addEventListener('change', function(){
            const patientId = this.value;
            fetch('{% url "get_patient_details" patient_id=0 %}'.replace('0', patientId), {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                },
            })
            .then(response => response.json())
            .then(data => {
                console.log(data['user'])
                displaySearchResults(data['user'])
            })
        })
    }
    
    // display search results of patients 
    function displaySearchResults(patients) {
        var searchResultsContainer = document.querySelector('.search-results');
        searchResultsContainer.innerHTML = '';

        patients.forEach(function (patient) {
            var patientContainer = document.createElement('div');
            patientContainer.classList.add('patient-container');

            // Profile picture
            var profilePicture = document.createElement('div');
            profilePicture.classList.add('profile-picture');
            var profile_picture_url = 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png';
            profilePicture.style.backgroundImage = 'url("' + profile_picture_url + '")';
            patientContainer.appendChild(profilePicture);

            // Patient details
            var patientDetails = document.createElement('div');
            patientDetails.classList.add('patient-details');
            var patientName = document.createElement('p');
            patientName.textContent = patient['name']; // patient name
            var patientEmail = document.createElement('p');
            patientEmail.textContent = patient['email']; //patient email
            patientDetails.appendChild(patientName);
            patientDetails.appendChild(patientEmail);
            patientContainer.appendChild(patientDetails);

            var chatButton = document.createElement('button');
            chatButton.classList.add('chat-button');
            chatButton.setAttribute('data-user-id', patient['id']);
            chatButton.textContent = 'CHAT';
            patientContainer.appendChild(chatButton);

            searchResultsContainer.appendChild(patientContainer);

            chatButton.addEventListener('click', function(e){
                e.preventDefault();
                var receiver_id = chatButton.getAttribute('data-user-id');
                var url = '{% url "chat:get_chat_session" receiver_id=0 %}'.replace('0', receiver_id);
                window.location.href = url;
            })
        });
    }

</script>

</body>
</html>