chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat_view, name="chat_view"),
    path("<int:receiver_id>/", views.get_chat_session, name="get_chat_session"),
    path("select-user", views.select_user_view, name="select_user_view"),
    path("pusher/auth/", views.pusher_authentication, name="pusher_authentication"),
    path("send-message/", views.send_message, name="send_message"),
]

healthConfig/urls.py
from django.contrib import admin
from django.urls import path, include
from healthScore import homepage_and_auth

urlpatterns = [
    path("", homepage_and_auth.homepage, name="homepage"),
    path("hs/", include("healthScore.urls")),
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls")),
]

healthScore/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import homepage_and_auth
from . import profile_view
from . import patient_view_records
from . import patient_submit_health_record
from . import healthcare_data
from . import community_data
from . import external_health_request_access
from . import admin_view_user_healthrecords
from . import doctor_data
from . import healthscore_admin_view


urlpatterns = [
    # Homepage and user auth
    path("homepage", homepage_and_auth.homepage, name="homepage"),
    path("registration/", homepage_and_auth.registration, name="registration"),
    path("login/", homepage_and_auth.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # Profile information
    path("editUserInfo", profile_view.edit_user_info, name="edit_user_info"),
    path("userInfo", profile_view.view_user_info, name="user_info"),
    # view records
    path(
        "viewRequests",
        patient_view_records.view_health_history_requests,
        name="view_requests",
    ),
    path(
        "viewHealthHistory",
        patient_view_records.view_health_history,
        name="view_health_history",
    ),
    path("viewReports", patient_view_records.view_report, name="view_reports"),
    path("getRecord/<str:rec_id>/", patient_view_records.get_record, name="get_record"),
    # Submitting health request apis
    path(
        "getDoctors/<str:hos_id>/",
        patient_submit_health_record.get_doctors,
        name="get_doctors",
    ),
    path(
        "getEdit/<str:rec_id>/", patient_submit_health_record.get_edit, name="get_edit"
    ),
    path(
        "edit-record/",
        patient_submit_health_record.edit_health_record_view,
        name="edit_record",
    ),
    path(
        "new-record/",
        patient_submit_health_record.add_health_record_view,
        name="new_health_record",
    ),
    path(
        "request-sent/",
        patient_submit_health_record.record_sent_view,
        name="new_health_record_sent",
    ),
    # Get healthcare related data
    path(
        "healthcareFacility/",
        healthcare_data.hospital_staff_directory,
        name="hospital_staff_directory",
    ),
    path(
        "getFacilityDoctors/",
        healthcare_data.get_facility_doctors,
        name="get_facility_doctors",
    ),
    path(
        "getFacilityAdmins/",
        healthcare_data.get_facility_admins,
        name="get_facility_admins",
    ),
    path(
        "addHealthcareStaff",
        healthcare_data.add_healthcare_staff,
        name="add_healthcare_staff",
    ),
    path(
        "deleteHealthcareStaff",
        healthcare_data.deactivate_healthcare_staff,
        name="deactivate_healthcare_staff",
    ),
    path(
        "activateHealthcareStaff",
        healthcare_data.activate_healthcare_staff,
        name="activate_healthcare_staff",
    ),
    path(
        "viewHealthHistoryDoc",
        patient_view_records.view_health_history_doc,
        name="view_health_history_doc",
    ),
    # community apis
    path("community/", community_data.community_home, name="community"),
    path("community/all-posts/", community_data.view_all_posts, name="all_posts"),
    path("community/my-posts/", community_data.view_my_posts, name="my_posts"),
    path("create-post", community_data.create_post, name="create_post"),
    path("edit-post/<int:post_id>/", community_data.edit_post, name="edit_post"),
    path("delete-post/<int:post_id>/", community_data.delete_post, name="delete_post"),
    path("view-post/<int:post_id>/", community_data.view_post, name="view_post"),
    path(
        "create-comments/<int:post_id>/comment/",
        community_data.create_comments,
        name="create_comments",
    ),
    path(
        "delete-comment/<int:comment_id>/",
        community_data.delete_comment,
        name="delete_comment",
    ),
    # External health request related apis
    path(
        "requestHealthHistory",
        external_health_request_access.request_health_history,
        name="request_health_history",
    ),
    path(
        "viewHealthHistoryAccessRequests",
        external_health_request_access.view_health_history_access_requests,
        name="view_health_history_access_requests",
    ),
    path(
        "update_request_status",
        external_health_request_access.update_request_status,
        name="update_request_status",
    ),
    path(
        "send-approval-emails",
        external_health_request_access.send_approval_emails,
        name="send_approval_emails",
    ),
    path(
        "send-reject-emails",
        external_health_request_access.send_rejection_emails,
        name="send_reject_emails",
    ),
    # health admin's view user records
    path(
        "recordDecision/",
        admin_view_user_healthrecords.view_healthworkers_user_record,
        name="view_healthworkers_user_record",
    ),
    path(
        "admin_view_records/",
        admin_view_user_healthrecords.admin_view_health_history_requests,
        name="admin_view_records",
    ),
    path(
        "adminGetEdit/<str:rec_id>/",
        admin_view_user_healthrecords.get_admin_edit,
        name="adminGetEdit",
    ),
    # Doctor related apis
    path("get_patients", doctor_data.get_patients, name="get_patients"),
    path(
        "get_doctor_details/<str:doctor_id>/",
        doctor_data.get_doctor_details,
        name="get_doctor_details",
    ),
    path(
        "get_patient_details/<str:patient_id>/",
        doctor_data.get_patient_details,
        name="get_patient_details",
    ),
    # healthScore admin apis
    path("hospitals/", healthscore_admin_view.list_hospitals, name="list_hospitals"),
    path(
        "hospitals/update_status/<int:hospital_id>/",
        healthscore_admin_view.update_hospital_status,
        name="update_hospital_status",
    ),
    path("userDashboard", homepage_and_auth.user_dashboard, name="user_dashboard"),
]

hospitalManagement/hospitalManagement/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

healthScore/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    PermissionsMixin,
    AbstractBaseUser,
)


STATUS_CHOICES = [
    ("approved", "Approved"),
    ("rejected", "Rejected"),
    ("pending", "Pending"),
]


# Create your models here.
class Hospital(models.Model):  # Viewed by healthScoreAdmin and hospitalAdmin
    id = models.AutoField(primary_key=True)
    name = models.TextField(null=False)
    address = models.TextField(null=False)
    contactInfo = models.TextField(null=False, max_length=10)
    status = models.TextField(choices=STATUS_CHOICES, default="pending")


class HospitalStaff(models.Model):  # Viewed by hospitalAdmin
    id = models.AutoField(primary_key=True)
    hospitalID = models.ForeignKey("hospital", to_field="id", on_delete=models.CASCADE)
    admin = models.BooleanField(default=False)  # True = hospitalAdmin, False = Doctor
    name = models.TextField(null=False)
    specialization = models.TextField(default="")
    contactInfo = models.TextField(default="", max_length=10)
    userID = models.IntegerField(null=False)
    securityQues = models.TextField(
        default=""
    )  # If we not doing email resetting password
    securityAns = models.TextField(
        default=""
    )  # If we not doing email resetting password


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid email address")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_patient(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_patient", True)
        return self._create_user(email, password, **extra_fields)

    def create_staff(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_patient", False)
        return self._create_user(email, password, **extra_fields)

    def create_healthcare_worker(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_patient", False)
        extra_fields.setdefault("is_healthcare_worker", True)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_healthcare_worker", False)
        extra_fields.setdefault("is_patient", False)
        extra_fields.setdefault("is_superuser", True)

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):  # Viewed by User
    id = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    password = models.TextField(null=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    is_healthcare_worker = models.BooleanField(default=False)

    last_login = models.DateTimeField(blank=True, null=True)

    name = models.TextField(blank=True, max_length=255, default="")
    dob = models.DateField(blank=True, null=True)
    contactInfo = models.TextField(default="", max_length=10)
    address = models.TextField(null=False)
    proofOfIdentity = models.TextField(
        null=False
    )  # Convert image to base64 string and store it here

    securityQues = models.TextField(
        default=""
    )  # If we not doing email resetting password
    securityAns = models.TextField(
        default=""
    )  # If we not doing email resetting password
    gender = models.TextField(
        blank=True, default=""
    )  # Can be updated to a choice field later on, if needed
    profilePic = models.TextField(
        null=True
    )  # Convert image to base64 string and store it here
    bloodGroup = models.TextField(null=False)
    requests = models.JSONField(
        null=True
    )  # Will store data in this form: [{ requestedBy: '', dateTime:'', status:''}]. Will have
    # the data of all the requests that have been done to view the user's records

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = CustomUserManager()

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_full_name(self):
        return self.name


class HealthRecord(models.Model):  # Viewed by User and hospitalStaff who are doctors
    id = models.AutoField(primary_key=True)
    doctorID = models.IntegerField(null=False)
    userID = models.ForeignKey("user", to_field="id", on_delete=models.CASCADE)
    hospitalID = models.IntegerField(null=False)
    status = models.TextField(choices=STATUS_CHOICES, default="pending")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now_add=True)
    appointmentId = models.ForeignKey(
        "appointment", to_field="id", on_delete=models.CASCADE
    )
    healthDocuments = models.JSONField(null=True)
    rejectedReason = models.TextField(null=True)


class Appointment(models.Model):  # Viewed by User and hospitalStaff who are doctors
    id = models.AutoField(primary_key=True)
    name = models.TextField(null=False)
    properties = models.JSONField(null=True)
    # Will store values such as below. Need not be only vaccines
    # {     # Can be a null field
    #     name  -> vaccine
    #     value -> covid
    # }


class CommunityInteraction(models.Model):
    userID = models.ForeignKey("user", to_field="id", on_delete=models.CASCADE)
    postID = models.AutoField(primary_key=True)
    postTitle = models.TextField(null=False)
    postDescription = models.TextField(default="")
    postTimeStamp = models.DateTimeField(auto_now_add=True)
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)
    tags = models.TextField(default="")
    postComments = models.JSONField(null=True)
    # These are the values that would be stored in the postComments jsonField
    # [{
    #     comment
    #     commentID
    #     commentTimeStamp
    #     commentUpvotes
    #     commentDownvotes
    #     userIdOfCommenter
    # }]


class Post(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    title = models.TextField(null=False)
    description = models.TextField(default="")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey("Post", related_name="comments", on_delete=models.CASCADE)
    commenter = models.ForeignKey("User", on_delete=models.CASCADE)
    content = models.TextField(default="")
    createdAt = models.DateTimeField(auto_now_add=True)


# 3rd Party requests
class HealthHistoryAccessRequest(models.Model):
    id = models.AutoField(primary_key=True)
    userID = models.ForeignKey("user", to_field="id", on_delete=models.CASCADE)
    status = models.TextField(choices=STATUS_CHOICES, default="pending")
    requestorName = models.TextField(null=False)
    requestorEmail = models.EmailField(null=False)
    purpose = models.TextField(null=False)
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now_add=True)

healthScore/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

healthScore/templates/community_home.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/css/bootstrap.min.css">
<title>Health Score</title>
<style>
    #topics_container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }
    .worker-icon {
    height: 30px;
    margin-left: 5px;
    }

    .topic {
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    .topic h2 {
        margin-top: 0;
    }
    .topic_content {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    .expand_topic {
        color: blue;
        cursor: pointer;
    }
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
    }
    h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    .post-list {
        margin-bottom: 30px;
        border-bottom: 1px solid #ccc;
        padding-bottom: 20px;
    }
    h3 {
        margin: 0;
    }
    p {
        margin-top: 10px;
        margin-bottom: 5px;
    }
    .expand_topic {
        text-align: right;
    }
    small {
        display: block;
        text-align: right;
        color: #888;
    }
    a {
        text-decoration: none;
        color: #007bff;
    }
    a:hover {
        text-decoration: underline;
    }
    .icon-bar {
            display: flex;
            justify-content: space-between;
    }
</style>
</head>

<body>
{%  include 'header.html' %}
    <div id="topics_container">
        <div class="icon-bar">
            <div class="btn-group">
                <button id="dropdownMenuButton" class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    {{headerTitle}}
                </button>
                <ul class="dropdown-menu dropdown-menu-lg-end">
                    <li><a id="allPosts" class="dropdown-item" href="{% url "all_posts" %}">All the posts</a></li>
                    <li><a id="myPosts" class="dropdown-item" href="{% url "my_posts" %}">My posts</a></li>
                </ul>
            </div>
            <div>
                <a href="{% url 'create_post' %}" class="btn btn-dark" role="button">Write a post</a>
            </div>
        </div>
        <ul>
            <li class="post-list"></li>
            {% for post in posts %}
            <li class="post-list">
                <h3>{{ post.title }}</h3>
                {% if post.is_healthcare_worker %}
                    <img src="https://i.imgur.com/MlFk11W.jpg" alt="Healthcare Worker" class="worker-icon" />
                {% endif %}
                {% load text_filters %}
                <p>{{ post.description|first_300_characters|linebreaks }}</p>
                <p class="expand_topic"><a href="{% url 'view_post' post.id %}">Read more ></a></p>
                <small>Date: {{ post.createdAt|date:"N j, Y, H:i:s" }}</small>
            </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        var dropdownMenuButton = document.getElementById('dropdownMenuButton');
        document.getElementById("allPosts").addEventListener("click", function(){
            dropdownMenuButton.textContent = this.textContent;
        })
        document.getElementById("myPosts").addEventListener("click", function(){
            dropdownMenuButton.textContent = this.textContent;
        })
    </script>
</body>
</html>

healthScore/templates/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Health Score</title>
<style>
    #topics_container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
        margin-top: 0;
        color: #000000;
    }
    label {
        font-weight: bold;
    }
    input[type="text"],
    textarea {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        resize: none;
    }
    textarea{
        height: 200px;
    }
    button[type="submit"] {
        background-color: #5B0888;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    button[type="submit"]:hover {
        background-color: #2d0444;
    }
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }
    header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px;
      background-color: #FFFFFF;
    }
    .logo {
      width: 350px;
      height: 100px;
    }
    .buttons {
      display: flex;
      gap: 15px;
      padding-right: 10px;
    }
    .register-button{
      background-color: #5B0888;
      font-size: 15px;
      color: #FFFFFF;
      border: none;
      padding: 10px 20px;
      border-radius: 10px;
      cursor: pointer;
    }
    .register-button:hover{
      background-color: #2d0444;
    }
    .login-button{
      background-color: transparent;
      font-size: 15px;
      color: #5B0888;
      font-weight: bold;
      border: none;
      padding: 10px 20px;
      border-radius: 20px;
      cursor: pointer;
    }
    .login-button:hover{
      color: #2d0444;
    }
    .user-dropdown {
      position: relative;
      display: inline-block;
    }
    .user-button {
      background: transparent;
      border: none;
      cursor: pointer;
    }

    .user-dropdown-content {
      display: none;
      position: absolute;
      right: 0;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .user-dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .user-dropdown-content a:hover {background-color: #f1f1f1}

    .user-dropdown:hover .user-dropdown-content {
      display: block;
    }
</style>
</head>

  
  
<body>
{%  include 'header.html' %}
<br><br>

{% block content %}
<div id="topics_container">
    <h1>Post New Topic</h1>
    <form id="new-post-form" method = "post">
        {% csrf_token %}

        <label for="id_title">Title:</label><br>
        <input type="text" id="id_title" name="title" required><br>

        <label for="id_description">Content:</label><br>
        <textarea id="id_description" name="description" rows="4" required></textarea><br>

        <button type="submit">Post</button>
    </form>
</div>
{% endblock %}


</body>
</html>

healthScore/templates/post_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Health Score</title>
<style>
    #topics_container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
        margin-top: 0;
        color: #000000;
    }
    label {
        font-weight: bold;
    }
    input[type="text"],
    textarea {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        resize: none;
    }
    textarea{
        height: 200px;
    }
    button[type="submit"] {
        background-color: #5B0888;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    button[type="submit"]:hover {
        background-color: #2d0444;
    }
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }
    header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px;
      background-color: #FFFFFF;
    }
    .logo {
      width: 350px;
      height: 100px;
    }
    .buttons {
      display: flex;
      gap: 15px;
      padding-right: 10px;
    }
    .register-button{
      background-color: #5B0888;
      font-size: 15px;
      color: #FFFFFF;
      border: none;
      padding: 10px 20px;
      border-radius: 10px;
      cursor: pointer;
    }
    .register-button:hover{
      background-color: #2d0444;
    }
    .login-button{
      background-color: transparent;
      font-size: 15px;
      color: #5B0888;
      font-weight: bold;
      border: none;
      padding: 10px 20px;
      border-radius: 20px;
      cursor: pointer;
    }
    .login-button:hover{
      color: #2d0444;
    }
    .user-dropdown {
      position: relative;
      display: inline-block;
    }
    .user-button {
      background: transparent;
      border: none;
      cursor: pointer;
    }

    .user-dropdown-content {
      display: none;
      position: absolute;
      right: 0;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .user-dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .user-dropdown-content a:hover {background-color: #f1f1f1}

    .user-dropdown:hover .user-dropdown-content {
      display: block;
    }
</style>
</head>

  
  
<body>
{%  include 'header.html' %}
<br><br>

{% block content %}
<div id="topics_container">
    <h1>Edit Your Post</h1>
    <form id="new-post-form" method = "post">
        {% csrf_token %}

        <label for="id_title">Title:</label><br>
        <input type="text" id="id_title" name="title" required value="{{form.title.value}}"><br>

        <label for="id_description">Content:</label><br>
        <textarea id="id_description" name="description" rows="4" required>{{form.description.value}}</textarea><br>

        <button type="submit">Post</button>
    </form>
</div>
{% endblock %}


</body>
</html>

healthScore/templates/post_new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Post New Topic</title>
<style>
    #topics_container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
        margin-top: 0;
        color: #000000;
    }
    label {
        font-weight: bold;
    }
    input[type="text"],
    textarea {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        resize: none;
    }
    textarea{
        height: 200px;
    }
    button[type="submit"] {
        background-color: #5B0888;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    button[type="submit"]:hover {
        background-color: #2d0444;
    }
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }
    header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px;
      background-color: #FFFFFF;
    }
    .logo {
      width: 350px;
      height: 100px;
    }
    .buttons {
      display: flex;
      gap: 15px;
      padding-right: 10px;
    }
    .register-button{
      background-color: #5B0888;
      font-size: 15px;
      color: #FFFFFF;
      border: none;
      padding: 10px 20px;
      border-radius: 10px;
      cursor: pointer;
    }
    .register-button:hover{
      background-color: #2d0444;
    }
    .login-button{
      background-color: transparent;
      font-size: 15px;
      color: #5B0888;
      font-weight: bold;
      border: none;
      padding: 10px 20px;
      border-radius: 20px;
      cursor: pointer;
    }
    .login-button:hover{
      color: #2d0444;
    }
    .user-dropdown {
      position: relative;
      display: inline-block;
    }
    .user-button {
      background: transparent;
      border: none;
      cursor: pointer;
    }

    .user-dropdown-content {
      display: none;
      position: absolute;
      right: 0;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .user-dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
    }

    .user-dropdown-content a:hover {background-color: #f1f1f1}

    .user-dropdown:hover .user-dropdown-content {
      display: block;
    }
</style>
</head>

  
  
<body>
{%  include 'header.html' %}
<br><br>

{% block content %}
<div id="topics_container">
    <h1>Post New Topic</h1>
    <form id="new-post-form" method = "post">
        {% csrf_token %}

        <label for="id_title">Title:</label><br>
        <input type="text" id="id_title" name="title" required><br>

        <label for="id_description">Content:</label><br>
        <textarea id="id_description" name="description" rows="4" required></textarea><br>

        <button type="submit">Post</button>
    </form>
</div>
{% endblock %}


</body>
</html>